version: "3"
services:
  db:
    image: mysql/mysql-server:8.0.23
    container_name: mysql1
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: mi
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: whoscall
    ports:
      - "3306:3306"